### ISSUE TITLE
few things that broke with the last update, I think...

### ISSUE THREAD

**Issue by DianeNox** [scott2000/answerset#18]
I was confused just now because this, for example, used to work perfectly fine. I assume the last change broke a few things :/ There's a few more things sort of like this, I might just add the screenshots to this issue when I encounter them again. At the time I thought I just hadn't updated yet.
<img width="734" alt="Screenshot 2024-01-14 070755" src="https://github.com/scott2000/answerset/assets/51899303/37104cfb-f65a-430e-b7c1-3319976bd736">

I feel kinda bad tbh. But like, what's *not* reporting these gonna do?

**Comment by scott2000** [comment]
This is a really tricky issue. Basically, here are the steps the add-on follows:

1. Match each given answer to the closest answer choice
2. For each matched answer, find what parts are wrong/missing (using the same method as Anki normally does)
3. For some missing parts, allow them to be missing without marking it as an error (e.g. brackets and parts of alternatives separated by `/`)

For the previous issue (#16), there was an issue where on step 2 where it was ignoring spaces, so it marked the space as being missing incorrectly. I fixed this issue by changing how it does step 2 (now it doesn't ignore spaces when matching answers).

But now for some reason as a result of that change, on step 2 it decided that instead of `a/` being missing, it was actually `/a` that was missing here (since both options start with `a`). Then, in step 3, it decided that `/a` shouldn't be allowed to be missing because the `n` is immediately after it. I'll try to think of a solution that would allow both of these cases to work, but for now, I'd probably recommend using `a(n)` instead of `a/an`.

I would mainly expect this to happen when one option is a prefix/suffix of another option, but if there's any other cases where this is happening, please let me know! I appreciate the help in reporting these issues, since I want to make sure everything is working as well as possible. I'm sorry there's been so many of this kind of issue!

**Comment by scott2000** [comment]
Ok I think I found a solution that should allow both of these things to work properly. This issue seems like it was a result of how I tried to fix the previous issue (#16), so I decided to undo what I had changed and fix it a different way. The only issue I can find now is that instead of showing this:

<img width="639" alt="Old diff" src="https://github.com/scott2000/answerset/assets/5590720/b8253b0f-9fc0-4a78-baff-a31f013787a9">

Now it shows this (the space is marked as missing even if you type it):

<img width="645" alt="New diff" src="https://github.com/scott2000/answerset/assets/5590720/0f353e24-d5f7-49b2-8150-0303b2d0d9e5">

But that seems like a more minor issue.

It should be fine to write `a/an` now, but I think `an/a` would still be broken. Basically if one of the options is contained in the other option, then that option must be listed first (so `start/starting` would work fine, but `starting/start` wouldn't always work). This isn't ideal, but I can't think of a better solution right now.

I released a new version, so please test it out and let me know if you're still seeing issues.

**Comment by DianeNox** [comment]
Yeah, I don't at all mind the space not showing as a correct character as long as it's not marked as an error, so this looks good to me! The way I use this is that I just hit enter instead of a number key to quickly move through the cards, which if there is an error marked means it presses 1 which no, so yeah. As long as that doesn't happen, I am perfectly happy.

Thanks a bunch! I'll report anything else I encounter. There is one thing that I feel would be more enhancement than bug that I've been sitting on...

**Comment by DianeNox** [comment]
Will put that in a different issue, for now... Something kind of related to this is still happening :/ 

<img width="644" alt="Screenshot 2024-01-17 052551" src="https://github.com/scott2000/answerset/assets/51899303/4ceeffb6-e079-4b8c-a1d6-2a47f52ad0f4">

Hm... How difficult would it be to make the code treat words linked by "/" as a, I guess, a block? So that it only ever attempts to match to one of the words and then moves on?

**Comment by DianeNox** [comment]
Um. Also not sure what happened here.
<img width="763" alt="Screenshot 2024-01-17 053550" src="https://github.com/scott2000/answerset/assets/51899303/ffa8cb15-e4ad-4ea5-9066-aba216a5818a">

(Oh hey spelling error. Almost missed that.)

**Comment by scott2000** [comment]
Hmm yeah, that's a little bit more complicated, but I think I have an idea of how to do it. Basically instead of relying on the original differences found by Anki but picking which things to report as errors, I think I can just find the differences using a custom approach in the first place which is aware of slashes and brackets and stuff. This should make everything much more consistent. I'll see if it works and let you know when I release it.

**Comment by scott2000** [comment]
Ok, I think I hopefully fixed all of these issues fully. Instead of relying partially on the default algorithm for finding differences, I made a new algorithm which is fully aware of brackets and slashes and all of that, so it hopefully should work in all cases consistently now! Please try it when you get a chance and let me know if you see any issues.

**Comment by scott2000** [comment]
Actually wait, I think there's some issue with it that's causing it to not work when downloaded from the Anki website. I'm going to revert the changes and try to figure it out tomorrow.

**Comment by scott2000** [comment]
Ok it was actually a quick fix, so it should all be good now. Please try it out if you get a chance!

**Comment by DianeNox** [comment]
Oh my gosh I just noticed it doesn't care whether or not I capitalize anymore. I didn't even realize how much I needed that, thank you!!!

**Comment by scott2000** [comment]
Oh yeah that was another thing I changed! I'm glad you like it!
